apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp  # ⚠️ Must match the Deployment labels
  ports:
    - protocol: TCP
      port: 3000  # Service port
      targetPort: 3000  # Container port
  type: NodePort
